language: shell

env:
  global:
    - DEPS="hyperspy pyxem dask[array] h5py matplotlib numpy scikit-image scikit-learn scipy"
    - TEST_DEPS="pytest pytest-cov coveralls"

matrix:
  include:
    - env: export PYTHON=3.7
      os: linux
#    - env: export PYTHON=3.7
#      os: windows
#      language: shell
#    - env: export PYTHON=3.7
#      os: osx

sudo: True # for Miniconda

before_install:
  - source ./ci/travis_setup_conda_linux.sh

install:
  - source ./ci/travis_install_with_conda.sh
  - pip install .

script:
  - export MPLBACKEND=Agg
  - pytest --cov=kikuchipy

after_success:
  - coveralls
