# The setup of different files for installation and tests on different operating
# systems is based upon HyperSpy:
# https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/.travis.yml

language: shell

env:
  global:
    - ENV=conda
    - DEPS="hyperspy pyxem dask[array] h5py matplotlib numpy scikit-image scikit-learn scipy"
    - TEST_DEPS="pytest pytest-cov coveralls coverage==4.5.4"
    - PYTHON_CONDA=3.7

matrix:
  include:
    # Linux (Ubuntu)
    # conda
#    - os: linux
    # pip
    - os: linux
      language: python
      python: 3.7
      env: export ENV=pip

    # macOS
    # conda
#    - os: osx
    # pip
    - os: osx
      env: export ENV=pip
      addons:
        homebrew:
          packages:
            - python3

    # Windows
    # conda
#    - os: windows
#      env: PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:$PATH"
    # pip
#    - os: windows
#      env: export ENV=pip; PATH="/c/Python37:/c/Python37/Scripts:$PATH"

sudo: True # for Miniconda

before_install:
  # Set up conda for the different operating systems
  - if [ "$ENV" == conda ]; then
      source ./ci/travis_setup_conda_$TRAVIS_OS_NAME.sh;
    fi

install:
  # Install dependencies with conda or pip
  - source ./ci/travis_install_with_$ENV.sh

  # Install KikuchiPy
  - pip install -e .

script:
  - export MPLBACKEND=Agg
  - pytest --cov=kikuchipy

after_success:
  - coveralls
