language: generic

env:
  global:
    - DEPS="hyperspy pyxem dask[array] h5py matplotlib numpy scikit-image scikit-learn scipy"
    - TEST_DEPS="pytest pytest-cov coveralls"

matrix:
  include:
    - os: linux
      env: export PYTHON=3.7
      language: python
    - os: osx
      env: export PYTHON=3.7
      language: shell
    - os: windows
      env: export PYTHON=3.7
      language: shell

sudo: True # for Miniconda

before_install:
  - source ./ci/travis_setup_conda_$TRAVIS_OS_NAME.sh

install:
  - source ./ci/travis_install_with_conda.sh
  - pip install -e .

script:
  - export MPLBACKEND=Agg
  - pytest --cov=kikuchipy

after_success:
  - coveralls
