name: 'Merge main into develop'

on:
  push:
    branches:
      - main

jobs:
  merge-main-into-develop:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Merge main into develop
      uses: robotology/gh-action-nightly-merge@v1.3.3
      with:
        stable_branch: 'main'
        development_branch: 'develop'
        allow_ff: true
        allow_forks: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}