name: Test documentation notebooks

on:
  schedule:
    - cron: '15 6 * * 1'
  workflow_dispatch:
    workflow: "*"

env:
  MPLBACKEND: agg

jobs:
  test-documentation-notebooks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install package and dependencies
        shell: bash
        run: |
          pip install -U -e .'[doc,tests,viz]'
          pip install nbval

      - name: Display Python, pip and package versions
        run: |
          python -V
          pip -V
          pip list

      - name: Test documentation notebooks
        run: |
          ./doc/tutorials/run_nbval.sh
