name: Test documentation notebooks

on:
  schedule:
    - cron: '15 6 * * 1'
  workflow_dispatch:
    workflow: "*"

jobs:
  test-documentation-notebooks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      MPLBACKEND: agg
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Display versions
        run: |
          python -V
          pip -V

      - name: Install package and dependencies
        shell: bash
        run: |
          pip install -U -e .'[doc,tests,all]'
          pip install -U nbval pyopencl

      - name: Test documentation notebooks
        run: |
          ./doc/tutorials/run_nbval.sh
